[package]
edition = "2021"
name = "rust-kv"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
deepsize = "0.2.0"
itertools = "0.10.5"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4", "napi6"] }
napi-derive = "2.12.2"

rusqlite = "0.29.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
